import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRecoilState } from 'recoil'
import { IIngredient, IProductType, productState } from './state'
import { Swiper, SwiperSlide,  } from 'swiper/react'
import { Autoplay, Pagination, Navigation } from 'swiper/modules';
import 'swiper/css';
import 'swiper/css/autoplay';
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [products2,setProducts] = useRecoilState(productState);
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.Wrapper}`}>
        <div>
          <div className='big_banner'>
            <div><span className="highlight1">72H</span> TIME<br/>SALE</div>
            <div>
              여유 있게 쇼핑하기 좋은 주말에는 <br/>
              특가 상품들을 확인해보세요. <br/>
              <span className='highlight2'>최대 90% 할인</span><br/>
            </div>
          </div>
        </div>
        <div className='sub_banner'>
          <div className='image'>
            <Link href={`/product/1`}>  
              <div style={{background:'url(/images/donkastu2.jpg) 50% 50%', width:"100%", height:"200px"}}>

            </div>
            </Link>
          </div>
          <div className='button'>
            <Link href={`/product/1`}>  
            <button className="shopcart">
              <span className="material-symbols-outlined">
                shopping_cart
              </span><span>담기</span>
            </button>
            </Link>
          </div>
          <div className='description'>
            <Link href={`/product/1`}>  
            <div className='title'>{products2.list[0].name}</div>
            <div className='price'>
              <div>{products2.list[0].price}원</div>
              <div>
                <span>{products2.list[0].saleRate*100}%</span>&nbsp;
                <span>{products2.list[0].price * (1 - products2.list[0].saleRate)}원</span>
              </div>
            </div>
            </Link>
          </div>
        </div>
        <div className="Slide">
          <Swiper
          spaceBetween={0}
          slidesPerView={2.5}
          autoplay={{ delay: 2000 }}
          modules={[Autoplay]}
          >
          {products2.list?.map((product:IProductType, idx:number)=>{
            if(idx === 0){
              return (<></>)
            }else
            return (

            <SwiperSlide>
            <div className="product">
            <Link href={`/product/`+(idx+1)}>  
              <div className='image'>
                <img src={product.imgUrl}/>
              </div>
            </Link>
              <div className='button'>
              <Link href={`/product/`+(idx+1)}>  
                  <button>
                    <span className="material-symbols-outlined">
                      shopping_cart
                    </span><span>담기</span>
                  </button>
              </Link>
              </div>
              <div className='description'>
              <Link href={`/product/`+(idx+1)}>  
              <div className='title'>{product.name}</div>
                <div className='price'>
                  <div>{product.price}원</div>
                  <div>
                    <span>{product.saleRate*100}%</span>&nbsp;
                    <span>{product.price * (1 - product.saleRate)}원</span>
                  </div>
                </div>
              </Link>
              </div>
            </div>
            </SwiperSlide>
          )
          })}
          </Swiper>
        </div>
      </main>
    </>
  )
}
